### ISSUE TITLE
Project Update 

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore-C179#33]
It is requested to update the downstream project to the latest 2023.02.xx.

More to be done within this issue:
- [x] Create a production branch from the current master before starting the update work 
- [x] Create a tag release 1.0.0 from the current production branch
- [x] Perform the requested update on the master branch

**Comment by MV88** [comment]
@randomorder @EddyCatt I would need to get the ldap.properties well populated with final values.

can you send this to me?

**Comment by MV88** [comment]
@randomorder I also need some .env variables listed in geostore-spring-security.xml

```
export LDAP_URL=""
export LDAP_USER_SEARCH_CATEGORY=""
export LDAP_GROUPS=""
export LDAP_GROUP_SEARCH_BASE=""
export LDAP_ROLE_SEARCH_BASE=""
```
