### ISSUE TITLE
Project update - Devops tasks

### ISSUE THREAD

**Issue by MV88** [geosolutions-it/MapStore-C179#35]
## Documentation notes

- [ ] Check Readme file documentation steps
- [ ] Document the properties used by ldap. 
- [ ] Provide a sample (without credentials) of the variables to give an Idea of the final result.

## Deploy notes

During installation, take also into account to:
- [ ] create the missing categories on installation (PERMALINK, USERSESSION, TEMPLATE)
- [ ] database schema probably changed. make sure to update `geostore-datasource-ovr.properties` to automatically apply changes, or to apply the proper changes to the schema manually to the existing geostore.
```
### Automatic create-update database mode

geostoreEntityManagerFactory.jpaPropertyMap[hibernate.hbm2ddl.auto]=update 


**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Other... Please describe:


## Other useful information

**Comment by tdipisa** [comment]
@randomorder @EddyCatt I think we can close this. Can you confirm?
